version: '3.8'

services:
  api:
    image: fastapi-app:latest
    container_name: fastapi-api
    environment:
      - ENVIRONMENT=production
    expose:
      - "8081"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s